
debug_mode: True

# visible video precentage
video_per: .3
dataset:  smthng-smthng_v2
precision: mixed
data_dir: ./data/20bn-something-something-v2/
label_dir: ./labels/smthng-smthng/v2

num_samplers: 1
#num_latents: 256
frame_size: [100,176]
#frame_size: 224

# GPU-device related parser arguments & number of workers
workers: 4
gpus: [0]
head: none
#pool: ada
#strict_load: False
