
debug_mode: True

# visible video precentage
video_per: 1.
dataset:  HACS
precision: mixed
frame_len: 16
frame_size: 284
train_frame_interval: [1,2]
val_frame_interval: 2
batch_size: 64
long_cycles: False
short_cycles: False
optimiser: 'SGD'
lr_base: 0.1
lr_steps: [40,60,75,90]
lr_factor: 0.1
end_epoch': 120

# GPU-device related parser arguments
gpus: [0,1]
