
debug_mode: True

# visible video precentage
video_per: .4
dataset:  UCF-101
precision: mixed
data_dir: /media/deepthought/SCRATCH/UCF-101/UCF-101_videos
label_dir: /home/deepthought/Alex/labels/UCF-101/split1
pretrained_dir: ./pretrained_models/HACS/mtnet_xs.pth

# GPU-device related parser arguments & number of workers
gpus: [0,1]
workers: 8

# set batch size
batch_size: 32
frame_size: 224
