
debug_mode: True

# visible video precentage
video_per: .6
dataset:  UCF-101
precision: mixed
data_dir: /media/m2ssd_2TB/UCF-101_videos
label_dir: /media/m2ssd_1TB/labels/UCF-101/split1
pretrained_dir: ./pretrained_models/UCF-101/mtnet_xs.pth

# GPU-device related parser arguments & number of workers
workers: 8

# set batch size
batch_size: 32
frame_size: 224

# pooling
pool: max
