
debug_mode: True

# visible video precentage
video_per: .7
num_latents: 256
dataset:  UCF-101
precision: mixed
data_dir: /mnt/storage/scratch/kl21213/UCF-101/
label_dir: /mnt/storage/scratch/kl21213/labels/UCF-101/split1
pretrained_dir: /mnt/storage/scratch/kl21213/pretrained_models/UCF-101/mtnet_xs.pth

# GPU-device related parser arguments & number of workers
workers: 8

# set batch size
batch_size: 32
frame_size: 224
